### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by NicoGonzalez94** [ibrahimeric/TPO-RollingCode-77i-Front#6]
Buenas chicos! Como va? para continuar con la devolución del proyecto necesito que resuelvan este problema. Gracias.

https://github.com/ibrahimeric/TPO-RollingCode-77i-Front/assets/166792979/9b22caa7-3da1-47d4-839d-8e7190caa36f

**Comment by Lucas01v** [comment]
Buenas! Corregido el error de enrutamiento.
